output.. = target/classes/
bin.includes = META-INF/,\
               OSGI-INF/,\
               WEB-INF/web.xml,\
               viewer/,\
               .
source.. = src/
src.includes = pom.xml
javacDefaultEncoding.. = UTF-8
